cb-talent-development/employer-style-base

sass/variables/_colors.scss

This is not a PR I enjoy - We need a longer-term fix for this, after discussing solutions with Rob. The style guide, in its current incarnation, is not always web- or SASS-friendly. A rundown of the big'uns:
* There are a few too many color palette options
* It's unclear what's primary, secondary, tertiary, and primary/secondary accent. The primary vs secondary colors seem out of order
* There are colors referenced in portions of the guide that are not defined in the palettes
* It's unclear what the accents to the right of the primary palettes are for or where they're used
This PR invalidates some good variable naming in `employer` that must be restored: for example, instead of `.text--accent` using the aptly-named `$accent-primary` color variable, it uses `$secondary`. This is a stopgap …

Color Fixes

---

sass/variables/_colors.scss

EM92 requests making sticky nav link hover color lighter. Do not want to change the color globally b/c of different backgrounds. Creating new color and hover link variables for use on sticky nav and any future use.

EM92: Adding #6BC6E9 from style guide for use as a hover link color

---

sass/variables/_sizing.scss

May need better naming convention and more clean up. For example, do we still need a `$base-border-radius: 5px`? Should `$radio-border-radius` equal 50 and not a calculation?
Adding to list of things to consider and refactor

Change button border radii to 3px and add variable for 3px radii

---

sass/_base.scss
sass/_typography.scss
sass/directives/_link.scss
sass/variables/_colors.scss

- Add a new directive for link styles
- Apply directive in both typography and colors
- Typography stylesheet isn't used on this branch. It will be implemented with EM-383
- So wanted to update typography for when the link styles are merged into the in-progress typography branch, but also added the new links to colors so they could be used for now. They will be removed

EM-384: Create Link Extend and Update Link Styles

---

sass/_base.scss
sass/_forms.scss
sass/_typography.scss
sass/variables/_breakpoints.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

@toastercup @ElliottAYoung @kurtedelbrock 
- Implement the previously unused typography.scss
- Move typography and buttons out of employer-scope
- Update header styles per [style guide](https://app.frontify.com/d/6xYC97AVwz1E/style-guide#/basics/typography)
- Move type styles from [employer](https://github.com/cbdr/employer) to employer-style-base
- Add variables for font-weight, margin-bottom, small-font, UI elements
- Add heavy and light classes
- Move section padding variable to style-base
- Move employer breakpoints to style base

EM-383: Style Guide Updates: Typography

---

sass/_base.scss
sass/_content_grids.scss
sass/variables/_sizing.scss

- Creates a flexible, responsive and reusable image grid
- Images auto-size to fit 160x160px to help out content creators
Will replace the grid in use on http://stg.hiring.careerbuilder.com/recruitment-advertising/job-posting/integration-partners (will be manually updated by PO in prod)
( @toastercup @kurtedelbrock @ElliottAYoung )

EM-332: Featured Block Image

---

sass/_content_grids.scss

- Add `object-fit` for Safari which distorts images that are more tall than wide
- Make images slightly smaller so they'll fit in two columns on mobile

EM-322: Fix Image Size and Aspect-Ratio for Safari

---

sass/_base.scss
sass/_forms.scss
sass/_typography.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

- Comments out old form styles which will need to be updated but which were not in use; now importing the forms stylesheet into base.scss
- Updates form styling variables
- Add `input` styles from [UX style guide](https://app.frontify.com/d/6xYC97AVwz1E/style-guide#/ui-patterns/data-entry) v1
- Update typography.scss for form font-family and font-weight; add anchor blue color for input text
- Update sizing.scss with form font sizes and padding
- Add `$grey-semi-dark` color variable for placeholder text
- Update form border and border-radius styles
- Update base and form box shadows
- Adds new `.fieldset--large` styles -- a full-width form input with attached submit button
@kurtedelbrock @toastercup @ElliottAYoung

EM-378: Form Styles and Email Subscription Card

---

sass/_forms.scss
sass/_typography.scss
sass/variables/_sizing.scss

Created new group of spacing variables:
- `$base-spacing` is unchanged
- `$base-margin` (`$base-spacing / 2`) is unchanged
- Used for space inside and between boxes
- Created new variable `$type-margin` for headers and paragraphs
- Set it equal to 24px [per Stephanie Gaspary's comment in Jira](https://cb-content-enablement.atlassian.net/browse/EM-489?focusedCommentId=19000&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19000)
- Reading pages have styles that overwrite this standard margin, so they are unchanged and they aren't using the 24px margin
- On Reading pages: paragraph margins = 20px; headline margins vary and are proportional to the size of the headline
- Changed `$section-padding` (used on homepage sections) to 35px. It is independent of …

EM-489: Consistent Homepage Section Spacing

---

sass/_base.scss
sass/directives/_z_index.scss
sass/variables/_sizing.scss

@toastercup @ElliottAYoung 
* Adds Sass formula that returns an appropriate relative `z-index` value given certain inputs
* _Are the comments clear?_
* The formula prints an error if the arguments are wrong and the z-index property is just omitted so the site doesn't break. I'm undecided - it might be more clear if the site breaks and uses the native Rails errors
* The formula is a bit complex in that you have to create the lists for the 4 arguments, but it's an improvement in that we'll no longer have to determine our own z-index numbers given all of the layered elements on the site. We just list things in the order in which they should be layered and it's much more flexible.
* Removed `$base-z-index` variable because it was set to equal 0 and anything that needs to be explicitly set to …

EM-524: Z-index

---

sass/_boxes.scss
sass/directives/_speech_bubble.scss
sass/variables/_sizing.scss

- Add `$base-box-shadow-hover`
- Use `$base-box-shadow` and `$base-box-shadow-hover` -- which are defined here instead of in [Employer](https://github.com/cbdr/employer) -- in `sass/_boxes.scss`
- Add `border` to `speech_bubble` mixin since all current speech bubble instances use the same `border` style
@toastercup @ElliottAYoung

Speech bubble

---

sass/_base.scss
sass/_forms.scss
sass/directives/_gradients.scss
sass/directives/_headers.scss
sass/variables/_animations.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

- Add Headers mixin
- Initially had mixin to use for both home page and Jobs/product page(s), but there were enough minor differences that designers/POs wanted between the two header types so I made two mixins. I need to determine the things that all headers will have in common, extract that and refactor these
-  Form updates
- common margins for form elements
- `box-sixing: border-box` so that our padding doesn't make boxes too large
- Extracted non-text input CSS selectors (like `input[type="button"]`) from text input CSS selectors (like `input[type="search"]` and `input[type="email"]`) and am now using's Bourbon's `$all-text-inputs` variable for styling text inputs
-  Add `radio-toggle` and `autocomplete-dropdown` mixins
-  Rename `motion.scss` to `animation.scss` and add toggle button …

EM582: Hero Headers and Forms

---

sass/directives/_accordion.scss

@arelia @toastercup
Adds the `white-space: normal` property to Accordions so that the text will break (line-break) on mobile

Add white-space property for line breaks on Accordions

---

sass/_base.scss
sass/directives/_tables.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

This PR adds a set of mixins to assist applications in creating Flexbox Tables. The passing around of `$columns` is a tad messy, but we've discussed potential improvements for the future that will merit revisting once we implement another table. For now, however, this should be generic enough to serve our purposes. An upcoming PR will add this to our pattern guide, as well.

Flexbox Table Directive

---

sass/directives/_modals.scss

Puts the close button in the right position. Can't figure out how that was working without it on other popups.

Fixup: Add Position Releative to Popup-Modal

---

sass/_base.scss
sass/_tables.scss
sass/_tooltips.scss
sass/_typography.scss
sass/directives/_accents.scss
sass/directives/_speech_bubble.scss
sass/directives/_tables.scss
sass/directives/_tooltips.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

Includes
- Directives for tables with both row and column headers
- Also adds class for the Yes/No icons in tables
- Directives for tooltips
- Adds Lato italic regular font
- Mixin for `$small-strip`
- Adds parameters to `speech-bubble` mixin for choosing a pointer direction and size
Implemented in [Employer PR #594](https://github.com/cbdr/employer/pull/594)

EM-666: Tables and Tooltips (Jobs Compare Chart)

---

sass/variables/_sizing.scss

Adds two new variables for 404 giant header text `$large-header-text` and `$large-header-text--mobile`
Both are computed from the `$base-font-size`

EM-773: Create new variables for 404 Giant Text

---

sass/_base.scss
sass/_read_more.scss
sass/directives/_media.scss
sass/variables/_colors.scss

Implemented by Employer [#612](https://github.com/cbdr/employer/pull/612) and includes:
- Read More Toggle classes
- Made `read-more` mixin based on [PR578](https://github.com/cbdr/employer/pull/578). Turns out I didn’t need to, but now we have it.
- Read more uses classes instead of mixins because the toggle/checkbox uses the adjacent sibling selector >> so the classes need to refer to each other >> so the classes need to be static
- On `read-more__trigger` I'm not using the following which shows all text on desktop and only uses toggle on mobile b/c I thought it would be specific to APS and not all read mores (b/c i didn't need it in the Jobs Features read more, but then I realized that Jobs Feature read more is just a link not a toggle). When we eventually add more read mores we may …

EM-665: Jobs Features Section (Read More, Media Elements)

---

sass/directives/_tables.scss

@arelia @toastercup
Adds the `medium-screen-left-column` mixin to be used by Employer for the compare chart tables

EM-754: Add medium-screen-left-column Mixin

---

sass/directives/_carousels.scss
sass/variables/_colors.scss

Refactor and rework the flex properties of the testimonials carousel so that the image sits in a fixed width, consistent box - also create `$demon-grey`, which is great :+1:

EM-758: Testimonial Image Fix

---

sass/_base.scss
sass/directives/_flyout.scss
sass/variables/_breakpoints.scss
sass/variables/_sizing.scss

I change the top-nav break-points to account for the extra space the new user account widget takes up.

EM-850: Updated Nav Breakpoints For Top Nav User Icon

---

sass/directives/_accents.scss
sass/directives/_boxes.scss

- Remove `shadow` mixin in accents.scss b/c we're not using it and it doesn't comply with the style guide
- Update box mixin to match style guide
- Apply `box--component` mixin to `card--title` mixin (used for "home product category blocks")
**Home Product Category Blocks**
Applied to Employer in [PR#652](https://github.com/cbdr/employer/pull/652)

EM-849: Fix Box Styles

---

sass/directives/_boxes.scss

This is so that employer does not throw any missing mixin errors.

Switched Out Pop-Out Mixin With Component-Box

---

sass/variables/_sizing.scss

Use `rem`, not `em`, for fonts
Something I thought I'd done already. Ems allow fonts to scale relative to their container. We don't want that. We want our fonts to always match the pre-determined sizes listed at http://cb-talent-development.github.io/employer-style-base/#typography

Use rem for Fonts

---

sass/variables/_sizing.scss

Reverts cb-talent-development/employer-style-base#66
This change affected more than I anticipated and I didn't see the issues in the Wraith diffs :(
I still want to make this change, but later when I can review diffs more carefully and make a list of things to watch out for -- for instance button padding is calculated using font size so the change resized anything that is a button, including carousel dots:

Revert "Use rem for Fonts"

---

sass/directives/_flyout.scss

Secondary nav flyout needs to be positioned from right b/c when the user name changes it affects how far from the left the flyout needs to move, but from the right the positioning is consistent
Implemented in [Employer PR #670](https://github.com/cbdr/employer/pull/670)

EM-939: Add Param to Offset Flyout Left or Right

---

sass/_forms.scss

**Purpose:**
In a field-and-button-combined form field, like the email subscribe form, this changes the way the field and button determine their widths
* Field can now shrink, but it targets 100%, thus taking up as much space as is available, but not so much that the button doesn't fit
* Button sizes it self according to the amount of text it has, and doesn't shrink or grow
* On small screens, button is at least 50% of the screen size, per the original build of the email subscribe form, but button width is auto so that if it needs to be bigger than 50% width to fit it's text it grows to the size it needs
**JIRA:**
Stems from but is independent of [EM-939](https://cb-content-enablement.atlassian.net/browse/EM-939)
**Changes:**
* Changes to setup, Architectural changes, Migrations
* n/a
* …

EM-939: Refactor .fieldset--large

---

sass/_buttons.scss
sass/directives/_accents.scss
sass/directives/_button.scss
sass/variables/_colors.scss

Adds a few new variables and duplicates / modifies some mixins for the brand simplification toggle on 3/30
Notable Changes:
* Add `bs__small-strip` mixin for toggle
* Add two new colors
* Add alternate `bs__tertiary-button` for the new button styles, per @susan

EM-854: reduce number of product category boxes on homepage

---

sass/_forms.scss

**Purpose:**
* Per Susan, placeholders should no longer be italic
**JIRA:**
stems from but is independent of https://cb-content-enablement.atlassian.net/browse/EM-939
**Changes:**
* Changes to setup, Architectural changes, Migrations
* n/a
* bump patch version number
* Side effects
* n/a
**QA Links:**
n/a
* Specific pages to visit:
* Any page
* point your local Employer branch to this style base branch and view the email subscription form at the bottom of every page and/or the buy boxes on the Jobs (/recruiting-solutions/job-postings) page
* Responsive considerations
n/a
**Relevant PRs/Dependencies:**
n/a
**Additional Information**

Style: Placeholders Not Italic

---

bower.json
sass/directives/_boxes.scss
sass/directives/_gradients.scss
sass/directives/_headers.scss
sass/variables/_colors.scss

Includes Brand Simplification changes (can we omit this from releases?)
**Purpose:**
* Changes for homepage modernization and brand simplification
* new white gradient mixin
* new home header styles
* new colors
* new mixin for making stats bars
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-724
**Changes:**
* Changes to setup, Architectural changes, Migrations
* n/a
* all brand simplification updates should bump the major version number
* Side effects
* changes mixin name used for home header and changes the styles in that mixin
* Before (right) After (left)
**QA Links:**
[http://web.employer-1.development.c66.me/](http://web.employer-1.development.c66.me/)
* Specific pages to visit:
* Home page - …

EM-724: Modernizing Homepage

---

sass/directives/_accents.scss

Adds the return to top mixin to the accents directive for use in Employer :+1:

EM-941: Add Return to Top Arrow

---

sass/directives/_accents.scss

Increases the bottom positioning of the back to top button on mobile so that pressing it no longer opens the Safari iOS navigation menu. Got the idea for the approach from: https://www.eventbrite.com/engineering/mobile-safari-why/
QA Link (view on mobile): http://web.employer-2.development.c66.me/

EM-1116: back to top on mobile

---

sass/_buttons.scss
sass/directives/_flyout.scss
sass/variables/_animations.scss
sass/variables/_breakpoints.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

**Purpose:**
> As a user, I want to have a cleaner site experience so that my navigation is simpler and easier to use across the employer and resource sites.
* Several style updates to create new 2-part nav bar
* Updates to flyouts
Before:
After: 
* Breakpoints are much lower so everyone can see the full nav on a 13" screen
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1190
**Changes:**
* Changes to setup, Architectural changes, Migrations, Library changes, Side effects
* n/a
See https://github.com/cbdr/employer/pull/794
**QA Links:**
Signed In: http://web.employer-7.development.c66.me/
Signed Out: http://a01c3356.ngrok.io/
* any
* Behold the double nav
* Responsive considerations
* …

EM-1190: Double Nav

---

sass/directives/_flyout.scss

**Purpose:**
- Maintains rounded corners when last `a` tag in a `.flyout` is in `hover` `active` or `focus` state
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1190
**Changes:**
* Changes to setup, Architectural changes, Migrations, Library changes, Side effects
* n/a
Before:
After:
**QA Links:**
http://a01c3356.ngrok.io/
* any
* Hover over Browse Products
* Hover over the last item in Browse Products
* See that the bottom left and right corners of the flyout are still rounded
* Responsive considerations
n/a
**Relevant PRs/Dependencies:**
https://github.com/cb-talent-development/employer-style-base/pull/84
https://github.com/cbdr/employer/pull/794
**Additional Information**

EM-1190: Maintain Rounded Corners on Flyouts

---

sass/directives/_accents.scss
sass/directives/_gradients.scss

Adds the Divider Line mixin for use with the new Authority Stats section.
Relevant Employer PR: https://github.com/cbdr/employer/pull/839
Example:
Requested Mockup:

EM-1319: Authority Stat Section

---

sass/variables/_sizing.scss

A very simple tweak, changes the vertical padding for form inputs to make it the same size as the button size - reducing it `0.2em` from `0.6` to `0.4`

EM-1399: Make email capture field and button same height

---

sass/_forms.scss
sass/variables/_sizing.scss

Alternative fix for https://github.com/cb-talent-development/employer-style-base/pull/92
- This change appeared to make the input field too narrow and would have affected inputs other than the combined input + button
- Using flexbox instead so that input and button stretch to the same height within the `.fieldset--large` class
**Q/A Link**: http://7cf60a0c.ngrok.io
**Jira**: https://cb-content-enablement.atlassian.net/browse/EM-1399
**Related PR**: https://github.com/cb-talent-development/employer-style-base/pull/92

EM-1399: Adjust Input and Button Heights on .fieldset--large

---

bower.json
sass/_base.scss
sass/directives/_accents.scss
sass/directives/_headings.scss
sass/directives/_visual-guides.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

**Purpose:**
Adds a new stylesheet for visual overview sections like the example shown in the Jira below.
* The addition of _visual-guides.scss
* New mixin: `visual-guide-divider()` which adds styles for a simple center divider used for an overview section.
* New mixin: `visual-guide-row()` which adds boilerplate styles for each row in a visual flow that are laid out using an ordered list.
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1317
**Changes:**
* Changes to setup
* N/A
* New file: `_visual-guides.scss`
* Migrations
* N/A
* N/A
* Side effects
* N/A
* Before
N/A
* After
N/A
**QA Links:**
http://web.employer-2.development.c66.me/recruiting-solutions/small-business-subscription-plans-and-pricing
**How to …

EM-1317: Small Biz Visual Overview Section Mixins

---

sass/_base.scss
sass/directives/_tables.scss
sass/directives/_tabs.scss
sass/variables/_sizing.scss

**Purpose:**
> As a user looking to compare plans, I want to see a format the allows me to see the differences in features - at a glance, so I can pick the plan that is most appropriate for my business.
* Adds tabs and mobile table mixins
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1343
**Changes:**
* Changes to setup, Architectural changes, Migrations, Library changes, Side effects
*
* Before
n/a
* After
**QA Links:**
http://web.employer-7.development.c66.me/recruiting-solutions/small-business-subscription-plans-and-pricing
* http://web.employer-7.development.c66.me/recruiting-solutions/small-business-subscription-plans-and-pricing
* Toggle between Monthly/Annual and verify …

EM-1343: Mobile Compare Chart

---

.gitignore
README.md
package.json

This removes Bower support and migrates `employer-style-base` to Yarn/npm

Yarn/npm Migration

---

sass/directives/_headers.scss
sass/variables/_sizing.scss

**Purpose:**
> EM-1309: As a designer or a front end developer, I'd like the pages that use the "header_large" header partial to henceforth use the "header_large_solutions" partial (renaming the partial) so that going forward we have:
> EM-1306: As a designer or a front end developer, I'd like the product page headers to henceforth be known as "header_large" so that going forward we have
- a defined set of headers
- the same language for this header type
- generic, reusable components when we want to use this header type again
* I feel like this is an intermediate step between consolidating existing headers and making header large side and header large background the same thing. Right now these are two separate things per the stories, and they have significant differences in how the …

EM-1306 and EM-1309: Header Large with Background Image and with Side Image

---

package.json
sass/directives/_visual-guides.scss

**Purpose:**
> The Overview section of the Small Business subscription page was designed in a way that POs could remove one of the steps through IPE, but this is not working.
> 
> I can remove some (label and paragraph) but not others (headline). Also, when I remove the label copy and then add it back, it's no longer the correct color. It should be the dark anchor blue, but switches to demon gray. (See screen shot.) In talking to David, he thinks he will need to adjust how snippets are displayed so everything is in one box per step.
This ESB PR updates the Visual Guide mixin to use flexbox's ordering system. This allows a PO to reorganize the `<li>` elements whichever way they want without needing to edit the guts of these blocks. This will order those blocks based on even / odd rules.
I …

EM-1593: Small Biz Overview Section Refactor (ESB)

---

sass/selectors/_cta.scss

Fixes prod push issue: https://trello.com/c/jhdULg4p/65-offers-tab-fonts-are-not-the-same-weight-across-the-three-buttons
- `a` tags are bold by default. Two CTAs used `a` one uses a `div` (it needs to be a `button`)
- now anything with `.cta__action-link` is `font-weight: $font-weight-regular;`
- also replaced font size with one of our new variables (of equal value)

Fix: Make All CTA Fonts Regular Weight

---

sass/directives/02_base_components/_button.scss

Fixes prod push issues where buttons were using system font instead of Lato:
- https://trello.com/c/7s5Jjgfa/63-jobs-rdb-subs-faq-questions-need-to-be-lato-not-arial
- https://trello.com/c/89WRnDnM/64-jobs-rdb-cta-button-on-buy-box-cta-needs-to-be-lato-not-arial
- https://trello.com/c/Sty1KHAO/69-homepage-labels-on-featured-products-section-need-to-be-lato-not-arial
- https://trello.com/c/jaIIrK7d/68-newsletter-subscribe-box-font-is-wrong-for-cta-button
Adds `font-family` to the button mixin

Fix: Explicitly Set Button Font-Family to Lato

---

package.json
sass/_base.scss
sass/directives/00_variables/_breakpoints.scss
sass/directives/00_variables/_sizing.scss
sass/directives/02_base_components/_button.scss
sass/directives/02_base_components/_forms.scss
sass/directives/02_base_components/_pagination.scss
sass/directives/02_base_components/_type_styles.scss
sass/directives/03_components/_media.scss

Jira: https://cb-content-enablement.atlassian.net/browse/EM-1288
Employer PR: https://github.com/cbdr/employer/pull/930
* cleans up borders on text buttons (see before/after: https://screencast.com/t/t9ZWrkqm6o) and removes `:hover` `:active` `:focus` outline
* adds `cursor: pointer` to link styles
* adds search pagination and search list item mixins
* updates navigation breakpoints to include Search
* adds z-index param to `autocomplete-dropdown` mixin (which won't break anything (buy boxes) b/c there's a default value for the param)

EM-1288: Search Page Styles

---

package.json
sass/directives/02_base_components/_gradients.scss

**Purpose:**
> As a visitor, when I a section of Hiring Dot with a gradient, it doesn't look like it does on other browsers like how I see it on Safari.
* Uses our previously implemented user agent sniffing classes on `html` tag and directly targets iPhone and Windows browsers that are not Edge (i.e. IE). I'll ask POs if they'd like to include Edge b/c those gradients don't look great
*  Removed the non-blend version of imagegradient mixin because the blend version can be used for this (with `$mode: unset` argument)
* Removed browser prefixed versions of gradients to remove clutter for devs. On old browsers that we no longer support (IE 11-) it's not broken, it's just different (solid) so everybody wins 
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1164
**Changes:**
* …

EM-1164: Gradient Issues

---

sass/directives/00_variables/_sizing.scss
sass/directives/02_base_components/_modals.scss

**Purpose:**
> As a visitor to a page, when I see a product's features that has more info, I can click on a 'read more link' that opens a modal that allows me to see a section for imagery and a section for copy that lets me know more about a specific feature.
This PR does the following:
- Adds in variables controlling the product feature modal
- Adds in a theme for the default close button for our modals
Visit the link for more information about the modal:
https://github.com/cbdr/employer/pull/949

EM-1570: Product Feature Modal (ESB)

---

package.json
sass/directives/02_base_components/_tabs.scss

**Purpose:**
This simply adds in Arelia's fix to center the column headers as mentioned here - https://github.com/cbdr/employer/pull/956#issuecomment-321401857
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1449
**Notes:**
@arelia This ticket will be immediately merged. Just wanted to create the request for documentation.

EM-1449: Center Mobile Compare Chart Column Headers

---

package.json
sass/directives/00_variables/colors/_colors.scss

**Purpose**
> As a visitor, I want to see a more robust and informative product page for Applicant Tracking.
* Adds minor change to text buttons: instead of specifying an underline color for hover, etc., the color is now `currentColor` which will match whatever the text color is
* This is for the Applicant Tracking page, where the text button is on a dark background and so the text has been changed to white
**JIRA**
https://cb-content-enablement.atlassian.net/browse/EM-1689
http://web.employer-1.development.c66.me/recruiting-solutions/applicant-tracking/dummy
* http://web.employer-1.development.c66.me/recruiting-solutions/applicant-tracking/dummy
* See the "Watch the Overview" …

EM-1689: Applicant Tracking Page Template

---

package.json
sass/directives/02_base_components/accents/_accents.scss
sass/directives/03_components/_cards.scss

* Remove `@mixin bs-small-strip`
* Nothing in Employer used this, so no change to Employer
* Refactor `@mixin small-strip` to use a color parameter
* Added current color as default, so no change to anywhere this is used

EM-1145: Post Brand Simplification Clean Up (small-strip Refactor)

---

package.json
sass/_base.scss
sass/directives/02_base_components/boxes/_boxes.scss
sass/directives/02_base_components/boxes/boxes.hbs
sass/directives/02_base_components/price_per_time/README.md
sass/directives/02_base_components/price_per_time/_price_per_time.scss
sass/directives/02_base_components/price_per_time/price_per_time.hbs
sass/selectors/_boxes.scss
sass/selectors/_price_per_time.scss

**Purpose**
> As a customer visiting the Job Postings page and looking at my purchase options, I want to easily find a link to the Value Plans and see all Job Posting options within the Buy Box, so that my options are clear and easy to compare.
**JIRA**
https://cb-content-enablement.atlassian.net/browse/EM-1784
**Changes**
* Add `cta-box` mixin which is a box with a gradient background + our box styles (`padding`, `border-radius`)
* Add `price-per-time` mixin which is used on both Value Plans and the Small Biz Compare Chart
* 
* 
* 
* bump style base for new mixins
* Side effects
* n/a …

EM-1784: Jobs Buy Box Value Plans

---

package.json
sass/directives/03_components/accordion/_accordion.scss

The accordion__panel targeted P tags only for the `padding-bottom: 24px;` but since the FAQ panels will now have multiple elements it's best to add that padding to the div itself. 
Additionally P tags already had a `margin-bottom: 20px;`: 
Here is the difference: 
**Before:**
**after:**

Refactor: Remove Scoped Styling to P Tags For FAQ Panel

---

package.json
sass/directives/02_base_components/modals/_modals.scss
sass/directives/03_components/cards/_cards.scss

**Purpose**
> As a visitor, I want to see the examples of the different types of Talent Networks available and I want to be able to sort through, click on an example to see more.
Because I figured that reusing Arelia's really nice card mixins for the new Gallery Widget would be great, this PR introduces some new modifications to `_cards.scss` to account for the Gallery Widget cards. Now these can simply be included anywhere in Employer to add some new flavor for additional galleries, whether they use `Mixitgallery` or not.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-204
**Changes**
* Adds a few new mixins targeting the Gallery Widget created for Employer / Cortex
* N/A
* N/A
* Migrations …

CE-204: Gallery Widget (ESB)

---

package.json
sass/directives/03_components/montage/_montage.scss

**Purpose**
This just adds in styling for the `Read More >>` link that was missing in the stories section of both the App Tracking and Talent Network pages.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-203
**Changes**
* See above
* N/A
* N/A
* The `Read More >>` link will need to be updated on Prod for both the App Tracking and Talent Network pages.
* N/A
* Side effects
* N/A
* Before
N/A
* After
http://dev.admin.cbcortex.com/
http://web.employer-1.development.c66.me/
* http://dev.admin.cbcortex.com/legacy#/webpages (`employer-1 talent …

CE-203: Talent Network Stories Section

---

package.json
sass/directives/03_components/headers/_headers.scss

**Purpose**
> As a visitor, I just want to make sure the page has all the jzugsh it needs to make me feel compelled to scroll, click things and ultimately buy a million dollars worth of products.
This modifies the `header--large--left` mixin so that it accept arguments to show/hide the CTA header text and to adjust the fonts for mobile.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-341
**Changes**
* The header mixin used (`header--large--left`) for the Applicant Tracking, Talent Discovery, and Talent Network was revised to use a boolean to show/hide the CTA and paragraph text on mobile and to use two new arguments to adjust the size of the fonts for mobile
* N/A
* N/A
* Migrations or Steps …

CE-341: Page Refactors (ESB)

---

sass/directives/00_variables/typography/_typography.scss
sass/directives/02_base_components/headings/_headings.scss

**Purpose**
> As a visitor, I'd like to see a bit more breathing room below a product page's feature sub head and the listed features. Right now it feels jammed together.
The mixin `heading--section--w-subhead` had its bottom margin upped from 20px to 40px. This was to fix some problems (mainly with the Features section found on pages like Talent Network) where the margin was too small.
This mainly affects the style `.employer-section__header--subhead` which is being used on a number of pages and their associated sections.
Other styles that were affected in Employer and ESB are `.small-biz__benefits__banner-text` and `.heading--section--w-subhead`, which is found in the Selectors folder in ESB. These styles however not relevant to this change as they're not in use or the bottom margin is …

CE-394: Increase Margin of ESB Subhead

---

package.json
sass/_base.scss
sass/directives/02_base_components/headings/_headings.scss
sass/directives/04_utilities/_reset.scss

**Purpose**
> The titles on the product tile cards have a tendency to change from anchor blue to gray. We need to add a revised style for the product cards to prevent the `<h3>` from changing colors because, in one of the mixins used for these cards, it wasn't set up right to account for CKE dropping in `<p>` tags.
This PR adds in a new reset mixin to reset paragraphs to a default style. This mixin can be included elsewhere when needed.
In this case, the mixin `heading--item`, which controls the headers of the product cards, now includes this reset mixin to override paragraph styles for dropped in `<p>` tags by CKEditor.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-399
**Changes**
* The titles in the product cards should no longer turn grey
* No need to …

CE-399: Product Card Mixin Update

---

package.json
sass/directives/03_components/flyout/_flyout.scss

On mobile the subnav flyout had a few issues: 
**Before:**
http://web.employer-5.development.c66.me/recruiting-solutions/post-jobs
**After:**
http://web.employer-6.development.c66.me/recruiting-solutions/post-jobs

bugfix: Mobile SubNav Z-Index Issue

---

sass/selectors/_forms.scss

**Purpose**
We really don't have a class to use for radio button groups. This PR just adds in a basic radio button group class for use with Employer.
Per Stephanie, will not be using the radio buttons as a part of the example form below. But I still want to include this since we currently lack styling for radio buttons.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-555
**Changes**
* New radio button group class
* N/A
* N/A
* N/A
* N/A
* Side effects
* N/A
* Before
N/A
* After
N/A
http://web.employer-2.development.c66.me/
* …

CE-555: Radio Button Class

---

package.json
sass/directives/02_base_components/forms/_forms.scss
sass/selectors/_buttons.scss

**Purpose**
> Given I am on this route, https://hiring.careerbuilder.com/recruiting-solutions/post-job-online-now,
I see the new interactive header UI and not the old Buy Box
Per the Jira, this adds in styling and base states for the new Buy Header that may replace the Buy Box.
This PR includes the mixins for the incrementer group and a new styled error message.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-772
**Changes**
* New mixins for an incrementer group and error message
* N/A
* N/A
* N/A
* N/A
* Side effects
* N/A
* Before
* After
http://web.employer-4.development.c66.me/
**How to Verify …

CE-772: Kill Buy Box (UI Only, ESB)

---

sass/directives/00_variables/colors/_colors.scss
sass/directives/02_base_components/gradients/_gradients.scss
sass/selectors/_gradients.scss

**Purpose**
> As a PO / Director, I should be able to use / see new gradients across the site at my discretion.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-1498
**Changes**
* Four new gradients created in the stylebase - `deviantGradient` and `deviantGradient-2` and their transparent versions
* New stylebase update and version. Plan to merge in CE-1482 (MS IE Bug) in the stylebase as well which will be a part of `2.3.0`
* Need to run yarn install
* N/A
* Need to publish new ESB version
* Need to update `package.json` with new ESB version
* N/A
* Side effects
* N/A
* Before
N/A
* After …

CE-1498: New Gradients

---

sass/directives/03_components/flyout/_flyout.scss

**Purpose**
> As a user, I should not see list styling for items in the main navigation while using MS Edge or IE 11+.
This is an interesting bug that appears only in IE 11 and the latest of MS Edge and affects our usage of `list-style-type: none`. This only impacts `<li>` elements that are hidden from view using `display: none` as we're doing with the navigation. The browser 'forgets' that the `list-style-type` property exists and is not applied. Thus, when a user displays the menu, list styling still appears. 
See the following links for more information:
https://twitter.com/fremycompany/status/950856311083683840
https://github.com/webhintio/webhint.io/issues/210
(*solution*) https://stackoverflow.com/questions/20356311/internet-explorer-11-ignores-list-stylenone-on-the-first-load
The …

CE-1428: MS Edge / IE Nav Bug

---

sass/directives/00_variables/_top_bar.scss
sass/directives/00_variables/typography/_type_styles.scss
sass/directives/00_variables/typography/_typography.scss
sass/directives/02_base_components/button/_button.scss
sass/directives/02_base_components/forms/_forms.scss
sass/directives/02_base_components/headings/_headings.scss

**Purpose**
> The content on the hiring.careerbuilder.com site is too small to read and does not match the UX guidelines for the pages.
This PR updates styling of our base font sizes so that they are bigger on the Hiring site. This includes adjustments to padding and the base font size of the style base. Some new font sizing variables were added to this as well.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-2343
**Changes**
* Font sizes of headers, paragraphs, and subheaders were increased for this project.
* N/A
* Font sizing variables were increased
* Padding adjusted for some containers like headers
* Verify that the site looks ok after release …

CE-2343: Style Base Fonts

---

sass/directives/02_base_components/headings/_headings.scss
sass/directives/03_components/headers/_headers.scss
sass/selectors/_typography.scss

**Purpose**
This PR refactors the Employer repo and the Style Base so that our H1 fonts are more consistent and easily manageable on the Hiring site.
In Part 1 we only focus on the H1 font as a demonstration, in Part 2, we plan to work on H2, H3, and P all at once.
In a Possible Part 3, we will address section elements and headers.
**JIRA**
https://careerbuilder.atlassian.net/browse/RDP-37186
**Changes**
* Developers can now simply use an H1 tag on any Hiring page without a worry of the Style Base or redundant fonts interfering 
* H1 font style is globally controlled by variables for both mobile and desktop, thus a developer simply needs to update the variables to update the website (unless page specific styles are overriding the H1 class, like in some cases where …

RDP-37186: H1 Style Base Refactor

---

sass/_base.scss
sass/directives/03_components/visual_guides/_visual_guides.scss
sass/selectors/_typography.scss

**Purpose**
This PR refactors the Employer repo and the Style Base so that our H2, H3, and P fonts are more consistent and easily manageable on the Hiring site.
**JIRA**
https://careerbuilder.atlassian.net/browse/RDP-39993
**Changes**
* Developers can now simply use an H2, H3, or P tag on any Hiring page without a worry of the Style Base or redundant fonts interfering
*Font style is globally controlled by variables for both mobile and desktop, thus a developer simply needs to update the variables to update the website (unless page specific styles are overriding the H2, H3, P class, like in some cases where the font is supposed to be white)
* Less dependence on the legacy Style Base
* New, refined common styles, easily located in the Employer repo
* Style guide was …

RDP-29507: H2/H3/P Tag Font Standards - Style Base
