sass/directives/_button.scss
sass/variables/_colors.scss

Color branding updates, second pass!
See:

Color Branding V2

---

sass/variables/_colors.scss

@arelia 
I swapped the color from $grey-darkest to $primary for $body-text-color per Stephanie's request

Change body text color to $primary

---

sass/_buttons.scss
sass/_typography.scss
sass/directives/_button.scss
sass/directives/_flashes.scss
sass/directives/_panels.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

These updates [implemented on Employer](https://github.com/cbdr/employer/pull/448)
- Updated colors!
- New color variables that describe color function!
- New buttons!
Quickly see the results with the [example style guide PR](https://github.com/cb-talent-development/employer-style-base/pull/19)
@kurtedelbrock @toastercup @ElliottAYoung

EM-383: Style Updates Pt1 - Colors

---

sass/_buttons.scss

@arelia 
Remap the secondary buttons per justin's request

Remap secondary buttons for now

---

sass/_boxes.scss

@arelia 
I added the tile box style I was working on in a new file called _boxes, let me know what you think?

Add tile boxes

---

sass/directives/_panels.scss

@toastercup @ElliottAYoung 
Adds modal extend for styling our popup backgrounds

EM-520: Add Modal Styles

---

sass/_forms.scss
sass/_typography.scss
sass/variables/_sizing.scss

Adds additional basic form styles

EM-541: Fix Contact Us Form

---

sass/variables/_colors.scss

@arelia 
I added a color because Stephanie wanted a different color for paragraph copy color, it just refers to an existing color, which matched the one she wanted

Add -text-color variable

---

sass/variables/_colors.scss

* Add `resource-carousel-button` colors

Resource Carousel Colors

---

sass/variables/_sizing.scss

The code comments indicate what values should belong to these variables. Using `rem`s makes that true in any context

Change base-spacing from em to rem for consistant sizing

---

sass/variables/_breakpoints.scss

Fixup: Use variables for breakpoint values

---

sass/_forms.scss

Per Susan and what was designed for the Buy Box

Fixup: All Placeholders Are Italic Now

---

sass/directives/_boxes.scss
sass/directives/_button.scss
sass/variables/_animations.scss
sass/variables/_sizing.scss

@arelia 
Add mixins for the accordion styles covering both the boxes and the buttons necessary for a working accordion

Build Accordion Mixins

---

sass/directives/_accordion.scss

@arelia @toastercup 
Builds the FAQ Accordions to now match CB Main's FAQ Accordions

EM-578 CB Accordions

---

sass/variables/_sizing.scss

* Add re-usable `$vertical-rule-width` sizing variable

Jobs Testimonial Carousel

---

sass/_base.scss
sass/_forms.scss
sass/directives/_accordion.scss
sass/directives/_carousels.scss
sass/directives/_headers.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

* Adds custom select box styles
* Updates to product header (height, remove subhead text on mobile)
* Adds carousel mixins
@toastercup @ElliottAYoung

EM-629: Jobs Page Updates

---

sass/directives/_carousels.scss

@arelia @toastercup 
Consolidates core styles from the product and testimonial carousels for the new VWO tests of the product pages. Creates component mixins that are successfully passing the correct styles over to Hiring Dot

EM-757+758: Search Page Styles Consolidation

---

sass/directives/_media.scss

Removes `h3-font-size` from `--description`

EM-772: Remove styles for --description

---

sass/directives/_accordion.scss
sass/directives/_boxes.scss

For Employer [PR #649](https://github.com/cbdr/employer/pull/649) and [PR #622](https://github.com/cbdr/employer/pull/622)
* Adds `sticky-box` mixin
* Refactors to accordions
* Adds `$breakpoint` parameter to `sticky-box` mixin

Refactor "Page with Buy-Box" Styles

---

sass/directives/_accents.scss
sass/directives/_boxes.scss
sass/directives/_tables.scss
sass/variables/_colors.scss

Creates mixins and styles for use with the new ecom product tables. Though the two are very similar, there are some key differences, notably the mobile behavior of these tables - hence these changes to the style base :+1:

EM-770: ecom promos page

---

sass/_base.scss
sass/_cta.scss
sass/variables/_sizing.scss

Here are classes needed for [employer/pull/675](https://github.com/cbdr/employer/pull/675)

EM-951: CTA Contact Styles

---

README.md

Adds instructions on what to do and how to update Employer after you've merged a PR

Add Versioning Instructions to README

---

sass/directives/_carousels.scss

Build three mixins:
* resource-header: To align the new carousel arrows on the top with the header of the carousel
* resource-carousel-arrow: The new styles for the resource carousel styles, places it in a box rather than on either side of the content
* resource-continue-block: The "Read Article" section with the RSS icon and whatnot, affixed to the bottom of the tile

EM-899: job optimizations 2

---

sass/directives/_carousels.scss

Fixes the mobile styles for the homepage logos carousel, no longer expects switching between carousels to function.

Fix Mobile Behavior for Logos Carousel

---

sass/directives/_gradients.scss
sass/variables/_colors.scss

I added new brand simplification color variables to `_colors.scss` and I created a new `imageBackgroundGradient` mixin in `_gradients.scss`. 
Desktop: 
Mobile:

EM-1107: New Homepage Demo Request Section

---

sass/directives/_carousels.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

This modifies the `resource-carousel-arrow` and `resource-continue-block` mixins as well as adds two new color variables needed for [employer/pull/734](https://github.com/cbdr/employer/pull/734)

EM-1048: Resource Section Refinements

---

sass/directives/_carousels.scss

- Updates headers on resource carousels where nav and header are combined
- Spaces nav and header differently without changing appearance
- Updates spacing on resource carousel arrows
Related to https://github.com/cbdr/employer/pull/806

EM-1169: Resource Carousel Cleanup

---

sass/directives/_accordion.scss
sass/variables/_sizing.scss

* Adds `$type-margin--small` variable for "label-style" type
* Adds `$accordion-angle-size` variable for accordion angles
* Adds `accordion-toggle--round` mixin for the circular toggle button
QA: http://web.employer-3.development.c66.me/recruiting-solutions/small-business-subscription-plans-and-pricing
Related PR: https://github.com/cbdr/employer/pull/855
Jira: https://cb-content-enablement.atlassian.net/browse/EM-1318

EM-1318: Small Biz Benefits

---

sass/directives/_accents.scss
sass/directives/_tables.scss
sass/directives/_tooltips.scss
sass/variables/_colors.scss
sass/variables/_sizing.scss

Several updates to tables
* Update table styles per [EM-1316](https://cb-content-enablement.atlassian.net/browse/EM-1316) from spaced columns to borders
**Before:**
**After:**
* Update `table--product` and `table--ecom` mixins to mostly just handle colors
* New `table__column-highlight` mixin for column highlight
* Rearranged style sheet so main components are on top, modifiers on bottom
* New variables for tables, font size and text color
Jira: https://cb-content-enablement.atlassian.net/browse/EM-1316
Employer PR: https://github.com/cbdr/employer/pull/872
QA: http://web.employer-7.development.c66.me/recruiting-solutions/small-business-subscription-plans-and-pricing

EM-1316: Small Biz Compare Chart

---

sass/directives/_visual-guides.scss
sass/variables/_sizing.scss

**Purpose:**
> As a user, I want to be presented with a (mobile) visual explanation of how I find candidates, so I believe finding candidates is easy and within reach.
This PR includes the visual-guide mobile styles required for EM-1344.
This PR also includes some refactoring updates, mainly the addition of a new base-spacing variable (`$base-spacing-xlarge`).
**JIRA:**
https://cb-content-enablement.atlassian.net/browse/EM-1344
**Changes:**
* Changes to setup
* Please see `Changes to setup` in https://github.com/cbdr/employer/pull/875
* Added: `$base-spacing-xlarge`
* Changed: `$base-spacing-large`
* Migrations
* N/A
* N/A
* Side effects
* N/A
* Before
N/A
* After
N/A
**QA Links:** …

EM-1344: Create Mobile Visual Overview (ESB, Cleanup)

---

sass/directives/_toggles.scss

I apologize to the mistake! But I did not notice one of the sass variables have changed. 
This fixes that.

fix: Update Toggle Button Transition Variable

---

sass/directives/_tables.scss

**Purpose:**
update compare chart checkmarks to green
**Prod Push Trello:**
https://trello.com/c/qCcMHvPv/53-chart-on-products-checkmarks-should-be-green-buttons-should-be-tertiary
**Employer**: https://github.com/cbdr/employer/pull/888

Fix: Update Compare Chart Checkmarks to Green

---

package.json
sass/directives/02_base_components/gradients/_gradients.scss
sass/directives/02_base_components/headings/_headings.scss
sass/directives/02_base_components/headings/headings.config.js
sass/directives/03_components/_visual-guides.scss
sass/directives/03_components/layout_split/_layout_split.scss
sass/selectors/_typography.scss

**Purpose**
> In the overview section, a visitor can see three unique copy and visual blocks that build upon one another, which mimics the experience created on the Subscriptions page.
**JIRA**
https://cb-content-enablement.atlassian.net/browse/EM-1690
**Changes**
* Moves common alignment styles from Employer to `text-image-panels--full-bleed-image` mixin
* Moves `:last-child` `margin` style from Employer to `visual-guide-row`
* Adds `heading--section--small`
* Adds logic to `imageGradientBlend` so that it renders correctly when used for photo image vs. pattern + blend, and so that it renders correctly for IE and iOS
* Changes to developer setup/environment, Architectural changes, Migrations or Steps to Take on Production
* n/a
* bumps style base …

EM-1690: Applicant Tracking Overview and Best Fit

---

package.json
sass/_base.scss
sass/directives/03_components/_features_list.scss
sass/directives/03_components/layout_quad/_layout_quad.scss

**Purpose**
The Why CB and Applicant Tracking page contain a list of features with icons that share a lot of the same styles and markup. This creates a mixin that supports both called `features_list`.
**JIRA**
https://cb-content-enablement.atlassian.net/browse/EM-1691
**Changes**
* Adds a `features_list` mixin that controls both layout and text styles (separated) to style up a list found on the WhyCB and App Tracking Page.
* N/A
* Adds `_features_list.scss`
* N/A
* N/A
* Side effects
* N/A
* Before
N/A
* After
N/A
http://web.employer-2.development.c66.me/recruiting-solutions/applicant-tracking/dummy …

EM-1691: Features List Mixin

---

package.json
sass/directives/03_components/_card_group.scss
sass/directives/03_components/_cards.scss

**Purpose**
This PR adds additional styles to a few mixins controlling the interactive cards found on the following pages:
- The home page
- Applicant Tracking
- Value Plans (small-biz)
- Why CB
**JIRA**
https://cb-content-enablement.atlassian.net/browse/EM-1693
**Changes**
* N/A
* N/A
* N/A
* N/A
* N/A
* Side effects
* N/A
* Before
N/A
* After
N/A
http://web.employer-6.development.c66.me/
* http://web.employer-6.development.c66.me/
* http://web.employer-6.development.c66.me/recruiting-solutions/applicant-tracking/dummy
* …

EM-1693: Interactive Card Updates

---

package.json
sass/directives/02_base_components/boxes/_boxes.scss

Move styles from Employer to here for `@mixin sticky-box`
Details and QA Server: https://github.com/cbdr/employer/pull/989

EM-1829: Refactors - De-dupe Buy Box Styles

---

package.json
sass/_base.scss
sass/directives/00_variables/typography/_typography.scss
sass/directives/03_components/montage/_montage.scss

**Purpose**
> As a visitor, I want to be wow'd by one beautiful client success story experience.
This PR adds in the montage mixin into ESB while making a few adjustments in Employer to account for this.
The main layout is a 4 column, 2 row grid using CSS grid (oh my) that can be manipulated easily by a PO using additional classes.
**JIRA**
https://cb-content-enablement.atlassian.net/browse/EM-1692
**Changes**
* N/A
* N/A
* N/A
* N/A
* N/A
* Side effects
* N/A
* Before
* After
http://web.employer-1.development.c66.me/recruiting-solutions/applicant-tracking/dummy
* Specific …

EM-1692: App Tracking Page - Customer Stories (ESB)

---

package.json
sass/selectors/_forms.scss

Added Demo Form layout classes.

CE-774: Add Support For Form Field Configuration

---

package.json
sass/_base.scss
sass/directives/00_variables/_sizing.scss
sass/directives/00_variables/typography/_typography.scss
sass/directives/03_components/layout_split/_layout_split.scss
sass/directives/03_components/layout_thirds/_layout_thirds.scss

* Adds `layout-thirds` layout style
* Adds consistent mobile image height for `layout-split`
* Bumps alpha version

CE-244 About Us

---

package.json
sass/selectors/_utilities.scss

**Purpose**
> As a user interested in our products on a mobile phone, I want to be able to find a Request Pricing demo form, so that I can get the information I need from a CB rep to make my purchase decision.
This PR adds two classes for a PO to use so that they can either hide or show an element for mobile.
```
hide-on-mobile
show-on-mobile
```
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-1376
**Changes**
* PO can use either `hide-on-mobile` or `show-on-mobile` to hide / show an element
**Relevant PRs/Dependencies**
* https://github.com/cbdr/employer/pull/1131

CE-1376: Hide / Show on Mobile Classes

---

sass/directives/03_components/card_group/_card_group.scss

**Purpose**
This PR introduces a new, fourth top bar color for the interactive cards seen on the Why CB page and the new Product Release page.
**JIRA**
https://careerbuilder.atlassian.net/browse/CE-1452 (rough mock, rough copy, a note about the video link)
**Changes**
* New bar color (purple) for the cards (ESB)
* `package.json` updated for the ESB patch
* Before
N/A
* After
http://web.employer-4.development.c66.me/
* http://web.employer-4.development.c66.me/company/product-releases
* Click on the 4th tile in the first section to see the new color.
**Relevant PRs/Dependencies**
* …

CE-1453/1452: Product Release Page (ESB)

---

sass/directives/00_variables/_sizing.scss
sass/directives/00_variables/_top_bar.scss
sass/directives/00_variables/colors/_colors.scss
sass/directives/00_variables/typography/_type_styles.scss
sass/directives/00_variables/typography/_typography.scss
sass/directives/02_base_components/button/_button.scss
sass/directives/02_base_components/headings/_headings.scss
sass/directives/03_components/layout_quad/_layout_quad.scss
sass/directives/03_components/layout_split/_layout_split.scss
sass/directives/03_components/visual_guides/_visual_guides.scss
sass/selectors/_typography.scss

Setting this PR up for now for everyone to begin reviewing as we AB test the site. Please leave comments or questions. Will be adding additional information in a few.
This is the upgrade to our style base for this new redesign.
Main PR can be found here -

CE-2254 / CE-2845: Hiring Redesign Stylebase Upgrade

---

sass/_base.scss
sass/directives/00_variables/_sizing.scss
sass/directives/00_variables/_top_bar.scss
sass/directives/00_variables/colors/_colors.scss
sass/directives/00_variables/typography/_type_styles.scss
sass/directives/00_variables/typography/_typography.scss
sass/directives/02_base_components/button/_button.scss
sass/directives/02_base_components/button/_video_controls.scss
sass/directives/02_base_components/headings/_headings.scss
sass/directives/03_components/accordion/_accordion.scss
sass/directives/03_components/features_list/_features_list.scss
sass/directives/03_components/headers/_headers.scss
sass/directives/03_components/montage/_montage.scss
sass/selectors/_buttons.scss

This is the PR for the stylebase repo regarding the rebrand project.

Topic: CB Rebrand Stylebase
